import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIST = BASE_DIR / "client_dist"

WORKFLOW_URL = os.getenv(
    "N8N_WORKFLOW_URL",
    "https://n8n-kuno.169.58.4.250.sslip.io/webhook/video-trim",
)
WORKFLOW_METHOD = os.getenv("N8N_WORKFLOW_METHOD", "POST").strip().upper()
SUPABASE_URL = os.getenv("SUPABASE_URL", "https://kzhwjmdsmmrksatxpeec.supabase.co").rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "")
SUPABASE_ANON_KEY = os.getenv(
    "SUPABASE_ANON_KEY",
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6aHdqbWRzbW1ya3NhdHhwZWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTYwNjQsImV4cCI6MjA3MTEzMjA2NH0.EiqndjLjszrf9v_gCIQelceCLUiQloL51O6jS1psODY",
)
TRANSCRIPT_SCHEMA = os.getenv("TRANSCRIPT_SCHEMA", "transcript")
VIDEOS_TABLE = os.getenv("TRANSCRIPT_VIDEOS_TABLE", "videos")
SEGMENTS_TABLE = os.getenv("TRANSCRIPT_SEGMENTS_TABLE", "segments")
VIDEOS_URL_COLUMN = os.getenv("TRANSCRIPT_VIDEOS_URL_COLUMN", "url")
VIDEOS_SOURCE_COLUMN = os.getenv("TRANSCRIPT_VIDEOS_SOURCE_COLUMN", "source")
SEGMENTS_VIDEO_ID_COLUMN = os.getenv("TRANSCRIPT_VIDEO_ID_COLUMN", "video_id")
SEGMENTS_ORDER_COLUMN = os.getenv("TRANSCRIPT_ORDER_COLUMN", "segment_number")
WORKFLOW_TIMEOUT_SECONDS = int(os.getenv("WORKFLOW_TIMEOUT_SECONDS", "300"))
WORKFLOW_POLL_SECONDS = int(os.getenv("WORKFLOW_POLL_SECONDS", "5"))
N8N_REQUEST_TIMEOUT_SECONDS = int(os.getenv("N8N_REQUEST_TIMEOUT_SECONDS", "7200"))
SEGMENTS_WAIT_TIMEOUT_SECONDS = int(os.getenv("SEGMENTS_WAIT_TIMEOUT_SECONDS", "0"))
WHISPER_MODEL_NAME = os.getenv("WHISPER_MODEL_NAME", "tiny")
WHISPER_MIN_OVERLAP = float(os.getenv("WHISPER_MIN_OVERLAP", "0.72"))
WHISPER_MIN_MATCH_COUNT = int(os.getenv("WHISPER_MIN_MATCH_COUNT", "6"))
WHISPER_SELECTION_MIN_SCORE = float(os.getenv("WHISPER_SELECTION_MIN_SCORE", "0.58"))
WHISPER_SELECTION_PADDING_BEFORE = float(os.getenv("WHISPER_SELECTION_PADDING_BEFORE", "0.00"))
WHISPER_SELECTION_PADDING_AFTER = float(os.getenv("WHISPER_SELECTION_PADDING_AFTER", "0.00"))
TRIM_MAX_CONCURRENCY = max(1, int(os.getenv("TRIM_MAX_CONCURRENCY", "2")))
TRIM_STATUS_TTL_SECONDS = max(60, int(os.getenv("TRIM_STATUS_TTL_SECONDS", "3600")))

